### ISSUE TITLE
composer 安装失败

### ISSUE THREAD

**Issue by andyzu** [smileymrking/laravel-gateway-worker#1]
composer require smileymrking/laravel-gateway-worker
Using version ^1.1 for smileymrking/laravel-gateway-worker
./composer.json has been updated
Running composer update smileymrking/laravel-gateway-worker
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires smileymrking/laravel-gateway-worker ^1.1 -> satisfiable by smileymrking/laravel-gateway-worker[1.1.0].
    - smileymrking/laravel-gateway-worker 1.1.0 requires illuminate/console ~5.5.0|~5.6.0|~5.7.0|~5.8.0|^6.18|^7.0 -> found illuminate/console[v5.5.0, ..., 5.8.x-dev, v6.18.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by smileymrking** [comment]
请提供一下 Laravel 版本。

**Comment by smileymrking** [comment]
如果使用的是 Laravel 8.x 可以尝试重新安装，刚刚已经发布了 v1.2 版本支持 8.x

**Comment by andyzu** [comment]
今天又尝试了一下，发现安装提示：
composer require smileymrking/laravel-gateway-worker
Using version ^1.2 for smileymrking/laravel-gateway-worker
./composer.json has been updated
Running composer update smileymrking/laravel-gateway-worker
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking smileymrking/laravel-gateway-worker (1.2.0)
  - Locking workerman/gateway-worker (v3.0.20)
  - Locking workerman/workerman (v4.0.19)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing workerman/workerman (v4.0.19): Extracting archive
  - Installing workerman/gateway-worker (v3.0.20): Extracting archive
  - Installing smileymrking/laravel-gateway-worker (1.2.0): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
Class SmileyMrKing\GatewayWorker\GatewayWorkerInterface located in ./vendor/smileymrking/laravel-gateway-worker/src/GatewayWorker/GatewayWorkerInterface.php does not comply with psr-4 autoloading standard. Skipping.
Class SmileyMrKing\GatewayWorker\Push\PushEvent located in ./vendor/smileymrking/laravel-gateway-worker/src/GatewayWorker/Push/PushEvent.php does not comply with psr-4 autoloading standard. Skipping.
Class SmileyMrKing\GatewayWorker\Push\Push located in ./vendor/smileymrking/laravel-gateway-worker/src/GatewayWorker/Push/Push.php does not comply with psr-4 autoloading standard. Skipping.
Class SmileyMrKing\GatewayWorker\GatewayWorkerTrait located in ./vendor/smileymrking/laravel-gateway-worker/src/GatewayWorker/GatewayWorkerTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class SmileyMrKing\GatewayWorker\GatewayWorkerService located in ./vendor/smileymrking/laravel-gateway-worker/src/GatewayWorker/GatewayWorkerService.php does not comply with psr-4 autoloading standard. Skipping.
Class SmileyMrKing\GatewayWorker\GatewayWorkerEvents located in ./vendor/smileymrking/laravel-gateway-worker/src/GatewayWorker/GatewayWorkerEvents.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: dcat/laravel-admin
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/sail
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: smileymrking/laravel-gateway-worker
Discovered Package: spatie/eloquent-sortable
Package manifest generated successfully.
76 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by andyzu** [comment]
但是无法启动：
php artisan gateway-worker push start

   Error

  Class 'SmileyMrKing\GatewayWorker\Push\Push' not found

  at vendor/smileymrking/laravel-gateway-worker/src/Commands/GatewayWorkerCommand.php:57
     53▕                 $argv[0] = 'gateway-worker ' . $serviceName;
     54▕                 $argv[1] = $action;
     55▕                 $argv[2] = $daemon;
     56▕
  ➜  57▕                 $service = new $class();
     58▕                 try {
     59▕                     $service->start();
     60▕                 } catch (\Exception $e) {
     61▕                     $this->error($e->getMessage());

      +13 vendor frames
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by andyzu** [comment]
我使用的 laravel 8.5

**Comment by smileymrking** [comment]
我已复现出该问题，是由于使用了 `composer 2` 的原因

**Comment by smileymrking** [comment]
@andyzu  已修复该问题，请升级到 1.3 版本

**Comment by andyzu** [comment]
感谢！
已经安装好了！求大神加我 QQ 可以不？ 270344899
