### ISSUE TITLE
关闭服务时 stop fail 然后会有两个僵尸进程

### ISSUE THREAD

**Issue by Neilyoz** [smileymrking/laravel-gateway-worker#2]
关闭服务时 stop fail 然后会有两个僵尸进程，请问作者遇到这个问题么

**Comment by smileymrking** [comment]
这个问题我目前没有遇到过，你可以看下这篇文章是否能够帮助到你
http://gongfuma.com/front/tech/detail/id/486.html
是否以 debug 方式启动的 workerman ，并在终端按了 `ctrl z` 给 workerman 发送了 `SIGSTOP` 信号，导致 workerman 进入后台并挂起(暂停)，所以无法响应 stop 命令( `SIGINT` 信号)
