### ISSUE TITLE
求作者写一个示例。

### ISSUE THREAD

**Issue by andyzu** [smileymrking/laravel-gateway-worker#3]
新手小白，对您的扩展很感兴趣，希望能有一个 demo 示例。

目前不知道如何在 controller 里开始下手，感觉好像还的装 getwayclient 才行。所以请大神指点！再次感谢！！！

**Comment by smileymrking** [comment]
`GetwayClient` 是在其他的业务项目上要装，本项目不需要装，具体使用方法与 `GatewayWorker` 项目完全一致，可以直接在 `Controller` 中使用 `GatewayWorker\Lib\Gateway` 类中的方法，具体使用方法可以直接阅读官方文档 http://doc2.workerman.net/lib-gateway-functions.html

**Comment by andyzu** [comment]
谢谢大神的指点！！！再次感谢

**Comment by andyzu** [comment]
大神，我按照您的提示，创建了一个 controller，在里面按照 http://doc2.workerman.net/on-connect.html 文档，写了一个onConnect方法。
然后运行了php artisan gateway-worker push start --d
controller 代码如下：

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use GatewayWorker\Lib\Gateway;


class TestController extends Controller
{

	public static function onConnect($client_id)
	{
		Gateway::sendToCurrentClient("Your client_id is $client_id");
	}
}


我 telnet 之后，系统只提示我了：
telnet 127.0.0.1 20010
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"type":"connect","client_id":"7f0000014e8400000001"}

难道我需要修改您的 vendor/smileymrking/laravel-getway-worker/src/GetWayWorker/GetWayWorkerEvents.php 里的 onConnect 方法，来调用我写的 onConnect 方法吗？
我感觉这样不对，请您告诉我正确的方法，谢谢大神。

**Comment by smileymrking** [comment]
可通过配置中的 `event_handler` 自定义 `onMessage` 、`onConnect`、`onClose` 等方法，参考 `READEME` 中自定义 `event_handler` 类部分
```
return [

    'push' => [
        # 设置使用哪个类来处理业务,业务类至少要实现onMessage静态方法，onConnect 和 onClose 静态方法可以不用实现
        'event_handler' => \App\GatewayWorker\Demo\DemoEvent::class,
    ],

];
```

**Comment by andyzu** [comment]
我已经按照您说的，仔细修改了 event_handler 的内容，再次感谢大神！希望大神别介意我一个菜鸟小白问的一些问题！！！

**Comment by andyzu** [comment]
再次请教大神：
如果我按照 config\gateway-worker.php 里的
`'ping_not_response_limit' => 1,   # 0 服务端主动发送心跳, 1 客户端主动发送心跳`
为 1 的时候，然后我 telnet 127.0.0.1 20010
显示如下信息：
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
你的 ID 是： 7f0000014e8400000002
{"type":"ping"}
Connection closed by foreign host.
```
然后当在默认的 55 秒后，显示完 {"type":"ping"} 再过一会就断开连接了。

但是如果我将 
`'ping_not_response_limit' => 1,   # 0 服务端主动发送心跳, 1 客户端主动发送心跳`
改成 0 的话，会一直 {"type":"ping"}，不会断开连接。

我的问题是：为什么不能设置成客户端主动发送心跳呢？

**Comment by smileymrking** [comment]
可以设置客户端主动发送，你虽设置为1，但客户端没有定时“主动”发送心跳的操作，超时后服务端就会自动断开，可参考文档 http://doc2.workerman.net/heartbeat.html

**Comment by andyzu** [comment]
按照您的提示，我写了如下的客户端。请大神过目，看是否有问题？
`
var ws = new WebSocket("ws://127.0.0.1:20010");
	ws.onopen = function(){
		console.info("与服务端连接成功");
		ws.send('test msg\n');//相当于发送一个初始化信息
		console.info("向服务端发送心跳包字符串");
		setInterval(show,55000);
	};

	function show(){
		ws.send('heart beat\n');
	}

	ws.onmessage = function(e){
		console.log(e.data);
	};
	//心跳处理
	//获取会员id
	ws.onclose = function(e){
		console.log(e);
	}
`

大神，主要是看 55 秒发送一次心跳包的形式对吗？

**Comment by smileymrking** [comment]
这种你可以直接去执行代码测试一下，符合你的预期就是对的

**Comment by andyzu** [comment]
已经测试，符合预期。

但是我发现，如果我将 
'ping_interval' => 0,  # 设置为 0 
'ping_not_response_limit' => 1,   # 0 服务端主动发送心跳, 1 客户端主动发送心跳

貌似就不会断开了。这应该不是 BUG 吧


备注：当然，肯定是需要心跳包的。

**Comment by smileymrking** [comment]
这个我这边倒是没有研究过，按其官方文档的说明，客户端心跳间隔时间范围在 `pingNotResponseLimit * pingInterval` 内，如果将 `ping_interval` 设置为 0 的话，按道理是需要实时发送心跳
